### ISSUE TITLE
Premium version 1.17 Doesn't work in Thermos 1.7.10

### ISSUE THREAD

**Issue by p1ut0nium** [Eniripsa96/SkillAPI#119]
SkillAPI Free 3.99 works great in 1.7.10 Thermos (forge/bukkit plugins), but I just bought the premium version and it fails to work. Here's the error I get in the console:

[17:00:13] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling SkillAPI v1.17 (Is it up to date?)
java.lang.NoClassDefFoundError: com/rit/sucy/config/parse/NumberParser
	at com.sucy.skill.data.Settings.loadItemSettings(Settings.java:896) ~[?:?]
	at com.sucy.skill.data.Settings.reload(Settings.java:98) ~[?:?]
	at com.sucy.skill.data.Settings.<init>(Settings.java:84) ~[?:?]
	at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by Eniripsa96** [comment]
This error is due to not using the most recent MCCore version.
